FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD quest-sesame2.jar /opt/quest-sesame2/
EXPOSE 8080
WORKDIR /opt/quest-sesame2/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "quest-sesame2.jar"]
